version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout
      - run:
          name: Get deps
          command: go get -d -t -v ./...
      - run:
          name: Build
          command: go build
      - run:
          name: Get cover
          command: go get golang.org/x/tools/cmd/cover
      - run:
          name: Get gocov
          command: go get -v github.com/axw/gocov/gocov
      - run:
          name: Get gocov
          command: go get -v github.com/mattn/goveralls
      - run:
          name: Test and cover
          command: goveralls -v -service=circle-ci -repotoken=$COVERALLS_TOKEN

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
